const itemChoices = document.querySelectorAll('.choice');
let selectedItem = 'clothes';
itemChoices.forEach(button => button.addEventListener('click', () => { itemChoices.forEach(item => item.classList.remove('active')); button.classList.add('active'); selectedItem = button.dataset.value; }));
const orgs = { clothes: { wearable: ['Goonj / Share At Door Step', 'Wearable clothes can be routed through a donation or collection partner.'], repairable: ['Repair or reuse first', 'A local tailor, clothing exchange, or donation partner may extend the item’s life.'], damaged: ['Respun / textile upcycling route', 'Torn clothing is better treated as textile material than as wearable donation.'], unusable: ['Textile recycling / upcycling route', 'End-of-life fabric should go to a partner that accepts non-wearable textiles.'] }, shoes: { wearable: ['GreenSole or footwear collection route', 'Good-condition footwear may be reused; confirm the current collection rules.'], repairable: ['Repair or reuse first', 'Repairing footwear usually keeps it in use longer than recycling it.'], damaged: ['GreenSole / footwear upcycling route', 'Damaged footwear needs a specialist route rather than a clothing donation bin.'], unusable: ['Responsible footwear recycling route', 'Separate footwear from fabric and verify the partner’s acceptance policy.'] }, textiles: { wearable: ['Reuse, repair or community exchange', 'Home textiles may have a second life through reuse or donation.'], repairable: ['Repair or upcycle locally', 'Repairing or transforming the material can avoid unnecessary disposal.'], damaged: ['Respun / textile recycling route', 'Damaged fabric can be sent for material recovery or upcycling.'], unusable: ['Textile recycling / responsible disposal', 'Use a textile-specific route and keep it separate from wet mixed waste.'] }, undergarments: { wearable: ['Verify specialised acceptance first', 'Do not send intimate garments as ordinary donations without confirmation.'], repairable: ['Reuse only where hygienically appropriate', 'Check the receiving organisation’s exact policy before handover.'], damaged: ['Respun / textile recycling route', 'Some textile partners accept used undergarments for material recovery; verify first.'], unusable: ['Responsible textile disposal route', 'Pack separately and confirm acceptance with a specialist partner.'] } };
function showRecommendation() {
  const condition = document.querySelector('#condition').value;
  const city = document.querySelector('#city').value.trim() || 'your city';
  const handover = document.querySelector('#handover').value;
  const [name, reason] = orgs[selectedItem][condition];
  const partner = selectedItem === 'shoes' ? ['GreenSole', 'https://greensolefoundation.com/'] : selectedItem === 'undergarments' || selectedItem === 'textiles' || condition === 'damaged' || condition === 'unusable' ? ['Respun', 'https://respunindia.com/'] : ['Goonj / Share At Door Step', 'https://goonj.org/'];
  const handoverText = handover === 'pickup' ? `Check whether pickup is currently available in ${city} on the partner website.` : handover === 'dropoff' ? `Find a verified drop-off point near ${city}.` : `Choose pickup or drop-off based on what is available near ${city}.`;
  const preparation = condition === 'wearable' ? 'Wash, dry and pack the items separately before donation.' : 'Clean and dry the items, separate footwear from fabric, and pack them securely.';
  document.querySelector('#result-card').innerHTML = `<div class="result-content"><div class="route-label">YOUR RESPONSIBLE ROUTE</div><h3>${name}</h3><p>${reason}</p><div class="recommendation"><strong>Next action</strong><span>${handoverText}</span></div><div class="partner-row"><div><strong>Suggested partner to check</strong><span>${partner[0]}</span></div><a class="partner-link" href="${partner[1]}" target="_blank" rel="noreferrer">Open official site <span>↗</span></a></div><div class="prep"><strong>Prepare the item</strong><span>${preparation}</span></div><div class="result-meta"><span class="tag">${selectedItem}</span><span class="tag">${condition}</span><span class="tag">${city}</span></div><p class="verify">The website button is a starting point, not a guarantee. Confirm that the organisation accepts your exact item and serves Pune before arranging pickup or visiting a drop-off point.</p></div>`;
  document.querySelector('#step-number').textContent = '3';
}document.querySelector('#recommend').addEventListener('click', showRecommendation);
function botReply(text) {
  const lower = text.toLowerCase();
  const cityMatch = text.match(/(Bengaluru|Bangalore|Mumbai|Delhi|Pune|Hyderabad|Chennai|Kolkata|Jaipur|Nagpur)/i);
  const city = cityMatch ? cityMatch[0] : 'your city';
  if (lower.includes('same') || lower.includes('different') || lower.includes('how do you')) return 'I should not give the same route for every item. I compare the item category, condition, city and handover preference. This demo uses local rules; IBM BOB is used to design and test the assistant workflow. A production version would connect to a verified live knowledge base.';
  if (lower.includes('what can you') || lower.includes('help') || lower.includes('how')) return 'I can help you decide whether an item should be donated, repaired, reused, upcycled, recycled or handled through responsible disposal. Tell me the item, its condition and your city.';
  let answer;
  if (lower.includes('shoe') || lower.includes('footwear')) {
    answer = lower.includes('good') || lower.includes('wearable') ? 'For wearable footwear, start with reuse or a footwear donation route. GreenSole may be relevant for footwear upcycling, subject to its current policy.' : 'For worn or damaged footwear, look for a specialist footwear upcycling or recycling route such as GreenSole. Do not place it in a normal clothing donation stream.';
  } else if (lower.includes('underwear') || lower.includes('undergarment')) {
    answer = 'Undergarments need special handling. Do not assume a normal donation centre will accept them. Check whether a textile-recovery partner such as Respun accepts them, and pack them clean and dry.';
  } else if (lower.includes('torn') || lower.includes('ragged') || lower.includes('damaged') || lower.includes('stain')) {
    answer = 'Torn, ragged or stained clothes are usually better suited to textile recovery or upcycling than wearable donation. Respun may be a relevant route, but confirm its current acceptance rules.';
  } else if (lower.includes('wearable') || lower.includes('clean') || lower.includes('good condition')) {
    answer = 'Clean, wearable clothes may be donated for reuse. Check a clothing collection partner such as Goonj or Share At Door Step, depending on availability in your city.';
  } else if (lower.includes('pickup') || lower.includes('collect')) {
    answer = 'Pickup depends on the organisation and city. I can shortlist a route, but you must verify the live pickup area and schedule through the official contact channel.';
  } else {
    answer = 'Please tell me whether you have clothes, shoes, fabric or undergarments, and whether they are wearable, repairable, torn or unusable. Then I can suggest a more specific route.';
  }
  return `${answer} For ${city}, clean and separate the items, then verify the organisation’s current accepted categories, drop-off location or pickup availability. I will not assume that every partner accepts every condition.`;
}
function addMessage(text, type) { const messages = document.querySelector('#messages'); const div = document.createElement('div'); div.className = `message ${type}`; div.textContent = text; messages.appendChild(div); messages.scrollTop = messages.scrollHeight; }
document.querySelector('#chat-form').addEventListener('submit', event => { event.preventDefault(); const input = document.querySelector('#chat-input'); const text = input.value.trim(); if (!text) return; addMessage(text, 'user'); input.value = ''; setTimeout(() => addMessage(botReply(text), 'bot'), 260); });
document.querySelectorAll('.suggestions button').forEach(button => button.addEventListener('click', () => { const input = document.querySelector('#chat-input'); input.value = button.dataset.question; input.focus(); }));

